name: my_album_app
description: Flutter app which shows list of Albums
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  retrofit: ^2.1.0
  dio: ^4.0.4
  cupertino_icons: ^1.0.4
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.0
  intl: ^0.18.0
  plugin_platform_interface: ^2.1.2
  rxdart: ^0.27.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
